### ISSUE TITLE
how to filter  commitlevel

### ISSUE THREAD

**Issue by qmhlan** [weeaa/goyser#5]
if err = streamClient.SubscribeTransaction("Transactions", &geyser_pb.SubscribeRequestFilterTransactions{
		AccountInclude: []string{subAccount},
		Vote:           func(b bool) *bool { return &b }(false), 
	}); err != nil {
		return err
	}
	
	SubscribeRequestFilterTransactions  have no  commitlevel,  how to filter   processed transaction ?

**Comment by weeaa** [comment]
hey, update to latest.
