### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zanville** [weeaa/goyser#7]
![image](https://github.com/user-attachments/assets/d7a22b92-6ce0-424d-9b6e-9c76d3546582)
![image](https://github.com/user-attachments/assets/e2848858-b088-4bf4-91d6-f1560ba4a4c1)

hey I recently tried using the updated version, and I get this error when trying to convert the transaction, I noticed the 
var tx rpc.GetTransactionResult is nil and not initialized. I tried doing that but it just continued to break more things

**Comment by weeaa** [comment]
hi there, i'll have a look v soon, apologizes

**Comment by weeaa** [comment]
hey, I've tested and it works on my end. lmk if you get any issues (also beware folder arch changed so your code may not work anymore, as I integrate jito geyser plugin)

**Comment by weeaa** [comment]
bump @CreditWorthy
